image: java:8-jdk

stages:
  - build
  - test

before_script:
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

lint:
  stage: test
  script:
   - ./gradlew lint

analysis:
   stage: test
   script:
    - ./gradlew findbugsMain findbugsTest

after_script:
  - echo "End CI"